test

diff --git a/.github/workflows/build-ampd-release.yaml b/.github/workflows/build-ampd-release.yaml
--- a/.github/workflows/build-ampd-release.yaml
+++ b/.github/workflows/build-ampd-release.yaml
@@ -98,32 +98,33 @@ jobs:
         working-directory: ./ampdbin
         run: |
           for binary in ./ampd-*; do
-            if [[ "$binary" != *.asc ]]; then
-              echo "Testing binary: $binary"
-              if [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
-                OUTPUT=$(file "$binary" | awk -F, '{print $1"," $2}')
-                if [[ "${{ matrix.arch }}" == "amd64" ]]; then
-                  EXPECTED="ELF 64-bit LSB pie executable, x86-64"
-                elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
-                  EXPECTED="ELF 64-bit LSB pie executable, ARM aarch64"
-                fi
-              elif [[ "${{ matrix.os }}" == "macos-12" ]]; then
-                OUTPUT=$(file "$binary")
-                if [[ "${{ matrix.arch }}" == "amd64" ]]; then
-                  EXPECTED="Mach-O 64-bit executable x86_64"
-                elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
-                  EXPECTED="Mach-O 64-bit executable arm64"
-                fi
+          if [[ "$binary" != *.asc ]]; then
+            echo "Testing binary: $binary"
+            OUTPUT=$(file "$binary" | cut -d: -f2- | awk -F, '{print $1"," $2}')
+            if [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
+              if [[ "${{ matrix.arch }}" == "amd64" ]]; then
+                EXPECTED="ELF 64-bit LSB pie executable, x86-64"
+              elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
+                EXPECTED="ELF 64-bit LSB pie executable, ARM aarch64"
               fi
-  
-              echo "Output: $OUTPUT"
-              echo "Expected: $EXPECTED"
-  
-              if [[ "$OUTPUT" == *"$EXPECTED"* ]]; then
-                echo "The binary format is correct."
-              else
-                echo "Error: The binary format does not match the expected format."
-                exit 1
+            elif [[ "${{ matrix.os }}" == "macos-12" ]]; then
+              OUTPUT=$(file "$binary" | cut -d: -f2-)
+              if [[ "${{ matrix.arch }}" == "amd64" ]]; then
+                EXPECTED="Mach-O 64-bit executable x86_64"
+              elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
+                EXPECTED="Mach-O 64-bit executable arm64"
               fi
             fi
+        
+            echo "Output: $OUTPUT"
+            echo "Expected: $EXPECTED"
+        
+            if [[ "$OUTPUT" == *"$EXPECTED"* ]]; then
+              echo "The binary format is correct."
+            else
+              echo "Error: The binary format does not match the expected format."
+              exit 1
+            fi
+          fi
           done
+        
